.TH JILO-WEB "8" "July 2024" "jilo-web 0.1"
.SH NAME
jilo-web \- PHP frontent to jilo (jitsi logs observer) database.
.SH DESCRIPTION
.B jilo-web
is a PHP app for searching through a jilo database.

You need a jilo database to have this package working. You can create the jilo database with the program 'jilo'.

.SH CONFIGURATION
The configuration file is /etc/jilo-web/jilo-web.conf.php.

.SH AUTHOR
Written and maintained by Yasen Pramatarov <yasen@lindeas.com>

.SH HOMEPAGE
https://lindeas.com/jilo

.SH VERSION
0.1

.SH SEE ALSO
jilo(8), jilo-cli(8)
